### PR TITLE
update to 6.0.2

### PR DESCRIPTION
**Pull request by lmartinez-mirror**
Hi, I originally wrote up this PR because of missing makedepends, but eventually it turned into a full rewrite.

You may have to write additional code for your GitHub Actions to extract the CHANGES.rst from the tarball, so I wouldn't merge this into master immediately.

* Package rewritten according to updated Python packaging guidelines
* Added CHANGES.rst from upstream
* Added cython to makedepends for optimized packages

### CODE REVIEW

**Comment by funilrys** [comment]
I'm not sure people are willing to use Cython. It's just a "plus" ...

**Comment by lmartinez-mirror** [comment]
python-box upstream recently added Cython support for compiling to C. I would argue it's more than a plus.

From the changelog, emphasis mine:

> Adding Cython support to *greatly speed up normal Box operations* on supported systems

With all due respect, a performance boost at the cost of temporarily downloading an additional package (solely for compiling) seems worth keeping around to me.

**Comment by funilrys** [comment]
Mhh Let's do it then. What's the state of your PR ?

**Comment by lmartinez-mirror** [comment]
The PR itself is finished, but it doesn't have any GitHub Actions code to extract the changelog.

**Comment by funilrys** [comment]
Great, let's break things.

**Pull request merged**
